### ISSUE TITLE
mario 64 rom

### ISSUE THREAD

**Issue by robertsammataro** [sparc-laboratories/sparclab.work#9]
were gonna get sued

**Comment by mwang840** [comment]
Lets Hope COE dean can pay for it

**Comment by blitzashspear** [comment]
Dear Mr. Sammmmmmmmmmmmmmmmmmmmmmataro,

RE: Notice of Legal Action for Copyright Infringement

I am writing to you on behalf of Nintendo of America Inc., regarding a serious matter of copyright infringement related to our intellectual property, specifically the video game Super Mario 64 for the Nintendo 64 system.

It has come to our attention that you have willfully and unlawfully posted a copy of Super Mario 64 online, which constitutes a clear violation of Nintendo's exclusive rights under the Copyright Act. This unauthorized distribution of our copyrighted material has caused substantial harm to Nintendo, including but not limited to, loss of profit, damage to our brand reputation, and infringement upon our intellectual property rights.

As you are likely aware, Nintendo is the rightful owner of the copyright in Super Mario 64, and we vigorously defend our intellectual property rights against any unauthorized use, reproduction, or distribution. Your actions not only violate the law but also undermine the hard work and creativity of our developers and artists who have contributed to the creation of this iconic game.

We demand that you immediately cease and desist from any further distribution, reproduction, or sharing of Super Mario 64 or any other copyrighted material owned by Nintendo. Furthermore, we require you to remove any infringing copies of the game from all online platforms and accounts under your control.

Please be advised that Nintendo reserves all rights to pursue legal action against you to enforce our intellectual property rights and seek appropriate remedies for the damages caused by your actions. This may include but is not limited to seeking monetary damages, injunctive relief, and recovery of attorney's fees and costs.

We strongly urge you to take this matter seriously and comply with our demands without delay to avoid further legal consequences. If you have any questions or require clarification regarding this matter, please do not hesitate to contact me directly.

Sincerely,
Nintendo of America.

**Comment by robertsammataro** [comment]
Fuck you
